version: "2"

services:

  sut:
    build:
      context: ./
      dockerfile: Dockerfile
    environment: 
      - REDIS_HOST=redis
    depends_on:
      - redis
      - unstable-redis

 sut-v4:
   build:
     context: ./
     dockerfile: Dockerfile-v4
   environment: 
     - REDIS_HOST=redis
   depends_on:
     - redis
     - unstable-redis

  redis:
    image: redis:3.2

  unstable-redis:
    build:
      context: ./unstable-redis/


