version: "2"

services:

  sut:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis

  sut-v4:
    build:
      context: ./
      dockerfile: Dockerfile-v4
    depends_on:
      - redis

  redis:
    image: redis:3.2


